In [58]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 

warnings.filterwarnings('ignore')

In [59]:
movies = pd.read_csv(r'data/tmdb_5000_movies.csv')
credits = pd.read_csv(r'data/tmdb_5000_credits.csv')

In [60]:
movies
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [61]:
print('Movie Shape : ', movies.shape)
print('Movies Credits : ', credits.shape)

Movie Shape :  (4803, 20)
Movies Credits :  (4803, 4)

In [62]:
print('\nMovies Columns : ')
print(movies.columns.tolist())

Movies Columns :
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

In [63]:
print('\nCredits Columns : ')
print(credits.columns.to_list())

Credits Columns :
['movie_id', 'title', 'cast', 'crew']

In [64]:
print('\nInformation about Movies')
print(movies.info())

Information about Movies
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB
None

In [65]:
print('\nInfomation about Credits : ')
print(credits.info())

Infomation about Credits :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB
None

In [66]:
print('\nMovies Missing Value : ')
print(movies.isna().sum().sort_values(ascending= False))

Movies Missing Value :
homepage                3091
tagline                  844
overview                   3
runtime                    2
release_date               1
budget                     0
vote_average               0
title                      0
status                     0
spoken_languages           0
revenue                    0
production_countries       0
genres                     0
production_companies       0
popularity                 0
original_title             0
original_language          0
keywords                   0
id                         0
vote_count                 0
dtype: int64

In [67]:
print('\nCredits Missing Values : ')
print(credits.isna().sum().sort_values(ascending= False))

Credits Missing Values :
movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [68]:
movies[['title', 'genres', 'keywords', 'overview']].head()

,title,genres,keywords,overview
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [69]:
credits[['title', 'cast', 'crew']].head()

,title,cast,crew
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [70]:
df= movies.merge(credits, left_on='id', right_on= 'movie_id')

In [71]:
print(df.shape)
df.head()

(4803, 24)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [72]:
df = df[['title_x', 'genres', 'keywords', 'overview', 'cast', 'crew']]

In [73]:
df.rename(columns= {'title_x' :'title'}, inplace= True)

In [74]:
df.head()

,title,genres,keywords,overview,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [75]:
df['genres'].iloc[0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [76]:
import ast as ast
ast.literal_eval(df['genres'].iloc[0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [77]:
# testing and trying this code 
[genre['name'] for genre in ast.literal_eval(df['genres'].iloc[0])]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [78]:
import ast

def convert_genres(text):
    return[genre['name'] for genre in ast.literal_eval(text)]
df['genres'] = df['genres'].apply(convert_genres)

In [79]:
def convert_keywords(text):
    return[keyword['name'] for keyword in ast.literal_eval(text)]
df['keywords'] = df['keywords'].apply(convert_keywords)

In [80]:
def convert_cast(text):
    return[]

In [81]:
df['cast'].iloc[0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [82]:
def convert_cast(text):
    return[cast['name'] for cast in ast.literal_eval(text)[:3]]
df['cast'] = df['cast'].apply(convert_cast)

In [83]:
df

,title,genres,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...
4798,El Mariachi,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry Bishé, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [84]:
def convert_crew(text):
    for crew in ast.literal_eval(text):
        if crew['job'] == 'Director':
            return crew['name']
df['crew'] = df['crew'].apply(convert_crew)

In [85]:
df['tags'] = (
    df['genres'].apply(lambda x: ' '.join(x)) + ' ' +
    df['keywords'].apply(lambda x: ' '.join(x)) + ' ' +
    df['overview'] + ' ' +
    df['cast'].apply(lambda x: ' '.join(x)) + ' ' +
    df['crew']
)

In [86]:
df

,title,genres,keywords,overview,cast,crew,tags
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron,Action Adventure Fantasy Science Fiction cultu...
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski,Adventure Fantasy Action ocean drug abuse exot...
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes,Action Adventure Crime spy based on novel secr...
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan,Action Crime Drama Thriller dc comics crime fi...
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton,Action Adventure Science Fiction based on nove...
...,...,...,...,...,...,...,...
4798,El Mariachi,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",Robert Rodriguez,Action Crime Thriller united states–mexico bar...
4799,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry Bishé, Marsha Dietlein]",Edward Burns,Comedy Romance A newlywed couple's honeymoon ...
4800,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]",Scott Smith,Comedy Drama Romance TV Movie date love at fir...
4801,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]",Daniel Hsia,When ambitious New York attorney Sam is sent...
4802,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]",Brian Herzlinger,Documentary obsession camcorder crush dream gi...

In [87]:
from sklearn.feature_extraction.text import CountVectorizer

In [88]:
df['tags'].isna().sum()

np.int64(33)

In [89]:
df['tags'] = df['tags'].fillna(' ')

In [90]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words= 'english')

In [91]:
vectors = cv.fit_transform(df['tags']).toarray()

In [92]:
from sklearn.neighbors import NearestNeighbors

In [93]:
knn = NearestNeighbors(n_neighbors=5, metric= 'cosine')
knn.fit(vectors)

NearestNeighbors(metric='cosine')

In [94]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [95]:
knn.kneighbors(vectors[0].reshape(1, -1))

(array([[4.44089210e-16, 5.19258849e-01, 5.66659169e-01, 5.71914663e-01,
         6.06318888e-01]]),
 array([[   0, 2403, 1531, 3158,  838]]))

In [96]:
distances, indices = knn.kneighbors(vectors[0].reshape(1, -1))
print(df.iloc[indices[0]]['title'])

0          Avatar
2403       Aliens
1531    Moonraker
3158        Alien
838        Alien³
Name: title, dtype: object

In [97]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\yash ohol\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\yash ohol\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\yash ohol\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\yash ohol\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\yash ohol\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\yash ohol\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [98]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [99]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [100]:
df['tags'] = df['tags'].apply(stem)

In [101]:
from sklearn.metrics.pairwise import cosine_similarity

In [102]:
similarity = cosine_similarity(vectors)

In [103]:
similarity[0]

array([1.        , 0.06839856, 0.04916051, ..., 0.03121953, 0.05309942,
       0.        ], shape=(4803,))

In [104]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

[(0, np.float64(0.9999999999999998)),
 (2403, np.float64(0.48074115106715354)),
 (1531, np.float64(0.4333408306443943)),
 (3158, np.float64(0.42808533691623324)),
 (838, np.float64(0.39368111183261656)),
 (4332, np.float64(0.38949041885226005)),
 (2015, np.float64(0.3841143835488626)),
 (373, np.float64(0.380442955126341)),
 (1914, np.float64(0.37121293493384755)),
 (461, np.float64(0.35942537872389224)),
 (1079, np.float64(0.3441236008058426)),
 (3534, np.float64(0.3406649843746013)),
 (2198, np.float64(0.340600604711478)),
 (278, np.float64(0.337961294022422)),
 (305, np.float64(0.3375152561397402)),
 (300, np.float64(0.3340495005622833)),
 (507, np.float64(0.3218981532296071)),
 (47, np.float64(0.3176117015830117)),
 (1318, np.float64(0.3163372442150344)),
 (158, np.float64(0.31544663407202245)),
 (1709, np.float64(0.3154466340720224)),
 (3730, np.float64(0.31512674583162725)),
 (4, np.float64(0.30602818624106143)),
 (239, np.float64(0.305887645160749)),
 (149, np.float64(0.30569749252782397)),
 (1352, np.float64(0.30380249716635904)),
 (2966, np.float64(0.30223526241349447)),
 (184, np.float64(0.30110815070511227)),
 (582, np.float64(0.29139711855430955)),
 (1354, np.float64(0.2912411862553588)),
 (1068, np.float64(0.2895889549703804)),
 (972, np.float64(0.28146312587632183)),
 (260, np.float64(0.28136571693556883)),
 (1201, np.float64(0.28136571693556883)),
 (94, np.float64(0.27912109783679506)),
 (539, np.float64(0.27912109783679506)),
 (1213, np.float64(0.27723070136732647)),
 (1951, np.float64(0.27348170645824377)),
 (1759, np.float64(0.2703274367816243)),
 (661, np.float64(0.2649064714130087)),
 (541, np.float64(0.2604940361258638)),
 (502, np.float64(0.2601329908572359)),
 (577, np.float64(0.25958499574503335)),
 (581, np.float64(0.25958499574503335)),
 (74, np.float64(0.2580927006043819)),
 (1341, np.float64(0.2569970264812942)),
 (322, np.float64(0.25685058345704065)),
 (95, np.float64(0.25391668753850405)),
 (1217, np.float64(0.25387276871303704)),
 (2967, np.float64(0.25335585485476586)),
 (770, np.float64(0.25166114784235827)),
 (56, np.float64(0.24722569302909875)),
 (1198, np.float64(0.24722569302909872)),
 (52, np.float64(0.2458025720041733)),
 (432, np.float64(0.24568115803183393)),
 (692, np.float64(0.24568115803183393)),
 (1959, np.float64(0.24520722313684196)),
 (150, np.float64(0.24216105241892621)),
 (549, np.float64(0.23893907643579956)),
 (2696, np.float64(0.23634505937372044)),
 (83, np.float64(0.2363450593737204)),
 (61, np.float64(0.2303696495604325)),
 (754, np.float64(0.22790142204853645)),
 (595, np.float64(0.22710998958306752)),
 (4042, np.float64(0.2266868175016326)),
 (1990, np.float64(0.22663483432464554)),
 (3143, np.float64(0.22571523745873384)),
 (228, np.float64(0.22487239817113241)),
 (1275, np.float64(0.22422074186848417)),
 (270, np.float64(0.22400538415856208)),
 (3668, np.float64(0.22269966704152222)),
 (557, np.float64(0.21654087871141106)),
 (1367, np.float64(0.2132808519406073)),
 (4187, np.float64(0.21073180760588114)),
 (1028, np.float64(0.2075143391598224)),
 (3624, np.float64(0.2075143391598224)),
 (773, np.float64(0.20602141085758227)),
 (91, np.float64(0.20468880508031637)),
 (3604, np.float64(0.20267783677525592)),
 (2541, np.float64(0.20232565955562795)),
 (1326, np.float64(0.20078234442307638)),
 (454, np.float64(0.2007387671367415)),
 (787, np.float64(0.20001778014849936)),
 (67, np.float64(0.19950596878025317)),
 (1650, np.float64(0.19867985355975654)),
 (236, np.float64(0.19751456577539828)),
 (778, np.float64(0.19751456577539828)),
 (230, np.float64(0.19736842105263155)),
 (1053, np.float64(0.19664205760333864)),
 (27, np.float64(0.19509974314292697)),
 (1294, np.float64(0.19466570535691502)),
 (141, np.float64(0.1938916835823703)),
 (306, np.float64(0.1938916835823703)),
 (1482, np.float64(0.1938916835823703)),
 (999, np.float64(0.19332886183313758)),
 (1473, np.float64(0.19251338527170497)),
 (1319, np.float64(0.1908854288927333)),
 (342, np.float64(0.19031442722792258)),
 (46, np.float64(0.18731716231633877)),
 (643, np.float64(0.18731716231633877)),
 (3405, np.float64(0.18604027516022803)),
 (626, np.float64(0.18560646746692377)),
 (1277, np.float64(0.18541926977182405)),
 (1662, np.float64(0.18405048238782)),
 (2912, np.float64(0.18394180184548975)),
 (1282, np.float64(0.18184158368223718)),
 (111, np.float64(0.1813690625275029)),
 (1490, np.float64(0.18067900652188354)),
 (35, np.float64(0.179968508266339)),
 (4593, np.float64(0.179968508266339)),
 (41, np.float64(0.1792043073268497)),
 (2327, np.float64(0.1792043073268497)),
 (3068, np.float64(0.17705013195704256)),
 (3214, np.float64(0.1745025152241333)),
 (233, np.float64(0.17342199390482396)),
 (680, np.float64(0.17331971020739498)),
 (564, np.float64(0.1731697435983527)),
 (87, np.float64(0.17292861596651865)),
 (108, np.float64(0.1720618004029213)),
 (1976, np.float64(0.1720618004029213)),
 (2229, np.float64(0.1720618004029213)),
 (1438, np.float64(0.17119059581558144)),
 (1377, np.float64(0.17073311796734164)),
 (26, np.float64(0.17013926184468012)),
 (1175, np.float64(0.17013926184468012)),
 (1390, np.float64(0.17013926184468012)),
 (222, np.float64(0.16993827032520067)),
 (931, np.float64(0.16972071444106068)),
 (942, np.float64(0.16972071444106068)),
 (2860, np.float64(0.16943474841747147)),
 (2444, np.float64(0.16912752287293456)),
 (3184, np.float64(0.1686133183583656)),
 (3427, np.float64(0.16742770563222895)),
 (168, np.float64(0.1655665446331305)),
 (740, np.float64(0.1642706150496122)),
 (36, np.float64(0.16386838133611553)),
 (1034, np.float64(0.16386838133611553)),
 (4339, np.float64(0.16305546992475287)),
 (1997, np.float64(0.16289594138375038)),
 (2782, np.float64(0.16222142113076252)),
 (4108, np.float64(0.16222142113076252)),
 (1272, np.float64(0.16122923187750418)),
 (2934, np.float64(0.16122923187750418)),
 (1106, np.float64(0.1611064840623164)),
 (579, np.float64(0.16062314155080887)),
 (3323, np.float64(0.16059101370939324)),
 (855, np.float64(0.16024705035571785)),
 (2509, np.float64(0.15929827321607742)),
 (208, np.float64(0.15789473684210523)),
 (3993, np.float64(0.1574724447330466)),
 (2781, np.float64(0.15743507142179688)),
 (889, np.float64(0.1573778950729267)),
 (1080, np.float64(0.15609763526361564)),
 (1922, np.float64(0.15609763526361564)),
 (3626, np.float64(0.15609763526361564)),
 (156, np.float64(0.1559797812375552)),
 (3445, np.float64(0.1556357543698668)),
 (2578, np.float64(0.15511334686589623)),
 (2815, np.float64(0.1546720562224365)),
 (401, np.float64(0.15389675281277312)),
 (4465, np.float64(0.1538967528127731)),
 (2726, np.float64(0.15294382258037448)),
 (1564, np.float64(0.15221477058564112)),
 (223, np.float64(0.1522147705856411)),
 (617, np.float64(0.15219519438202528)),
 (1877, np.float64(0.15190124858317955)),
 (249, np.float64(0.15174424466672098)),
 (1460, np.float64(0.15174424466672098)),
 (483, np.float64(0.15086285728094284)),
 (2757, np.float64(0.15058675831730728)),
 (2995, np.float64(0.15018785229652765)),
 (3724, np.float64(0.15018785229652765)),
 (1373, np.float64(0.14987146717098282)),
 (4542, np.float64(0.14974651178226572)),
 (5, np.float64(0.14933692277237473)),
 (31, np.float64(0.14933692277237473)),
 (200, np.float64(0.14886458551295736)),
 (800, np.float64(0.14886458551295736)),
 (1643, np.float64(0.14886458551295736)),
 (1016, np.float64(0.14870296936986563)),
 (101, np.float64(0.14808721943977307)),
 (2016, np.float64(0.14808721943977307)),
 (3439, np.float64(0.14808721943977307)),
 (939, np.float64(0.14757569038298454)),
 (2433, np.float64(0.14757569038298454)),
 (3813, np.float64(0.14748154320250398)),
 (642, np.float64(0.14686837386151166)),
 (628, np.float64(0.14673479641335554)),
 (456, np.float64(0.14667970544223286)),
 (2341, np.float64(0.14456082739572798)),
 (466, np.float64(0.1442149876003076)),
 (2129, np.float64(0.14379392104440059)),
 (587, np.float64(0.1433848336691011)),
 (4661, np.float64(0.1433148727800037)),
 (1358, np.float64(0.14286919170318604)),
 (2758, np.float64(0.1419620765529085)),
 (232, np.float64(0.14159846508095772)),
 (1094, np.float64(0.14159846508095772)),
 (490, np.float64(0.1404878717372541)),
 (4349, np.float64(0.1404878717372541)),
 (365, np.float64(0.14019850403200995)),
 (1652, np.float64(0.13977653617040256)),
 (2052, np.float64(0.13977653617040253)),
 (301, np.float64(0.13934101278298844)),
 (1440, np.float64(0.13920485060019283)),
 (2053, np.float64(0.13920485060019283)),
 (3953, np.float64(0.13834289277321493)),
 (755, np.float64(0.13809204416652684)),
 (2671, np.float64(0.1379563513841173)),
 (389, np.float64(0.13770565818881086)),
 (505, np.float64(0.13770565818881086)),
 (169, np.float64(0.13764944032233706)),
 (1583, np.float64(0.13679711361135388)),
 (2550, np.float64(0.1361331925293325)),
 (1735, np.float64(0.13606194139870567)),
 (473, np.float64(0.13555692745397502)),
 (592, np.float64(0.13555692745397502)),
 (220, np.float64(0.13530201829834765)),
 (1787, np.float64(0.13530201829834765)),
 (229, np.float64(0.13527771618440249)),
 (127, np.float64(0.13450689671224256)),
 (207, np.float64(0.13440323049513725)),
 (279, np.float64(0.13440323049513725)),
 (1825, np.float64(0.13440323049513725)),
 (1750, np.float64(0.1338548962820509)),
 (495, np.float64(0.13382584475782766)),
 (1188, np.float64(0.13245323570650436)),
 (1291, np.float64(0.1321815364753605)),
 (3815, np.float64(0.13200500012082497)),
 (2203, np.float64(0.13109470506889243)),
 (2241, np.float64(0.1302565123238377)),
 (7, np.float64(0.13006649542861798)),
 (1439, np.float64(0.12988108336653276)),
 (1158, np.float64(0.12977713690461)),
 (1468, np.float64(0.12857571271486287)),
 (1715, np.float64(0.12857571271486287)),
 (1191, np.float64(0.1284985132406471)),
 (2537, np.float64(0.12824729401064425)),
 (110, np.float64(0.12804983847550622)),
 (2650, np.float64(0.12780429685269148)),
 (14, np.float64(0.12725695259515554)),
 (2163, np.float64(0.12695834376925202)),
 (2898, np.float64(0.12667364798453498)),
 (18, np.float64(0.12617865362880898)),
 (480, np.float64(0.1260506983326509)),
 (2233, np.float64(0.1260506983326509)),
 (2936, np.float64(0.12590824129146974)),
 (487, np.float64(0.12565617248750865)),
 (1415, np.float64(0.12565617248750865)),
 (2069, np.float64(0.12540051368250327)),
 (1012, np.float64(0.12519334891679787)),
 (1796, np.float64(0.12519334891679787)),
 (599, np.float64(0.12513585483848821)),
 (3750, np.float64(0.12513585483848821)),
 (1015, np.float64(0.12487810821089251)),
 (2482, np.float64(0.12373764497794917)),
 (2884, np.float64(0.12372834943310805)),
 (2986, np.float64(0.12361284651454937)),
 (785, np.float64(0.12297974198582043)),
 (589, np.float64(0.12262786789699316)),
 (430, np.float64(0.12251987327639924)),
 (3904, np.float64(0.12244949999473091)),
 (362, np.float64(0.1224494999947309)),
 (3722, np.float64(0.1222789970111296)),
 (1405, np.float64(0.12159009577144937)),
 (2914, np.float64(0.12154742509255279)),
 (1554, np.float64(0.12154742509255277)),
 (70, np.float64(0.12105003117656306)),
 (1523, np.float64(0.1209127083516686)),
 (2727, np.float64(0.1209127083516686)),
 (1611, np.float64(0.12049504662575558)),
 (422, np.float64(0.11980845957463077)),
 (624, np.float64(0.11980845957463077)),
 (1932, np.float64(0.11946953821789977)),
 (1492, np.float64(0.11920791213585391)),
 (2278, np.float64(0.11846977555181845)),
 (529, np.float64(0.11838926601105419)),
 (1089, np.float64(0.11838926601105419)),
 (2614, np.float64(0.11803342130469505)),
 (3568, np.float64(0.11749469908920933)),
 (53, np.float64(0.11749469908920931)),
 (3287, np.float64(0.11712303424679456)),
 (72, np.float64(0.11712303424679454)),
 (568, np.float64(0.11712303424679454)),
 (102, np.float64(0.11654330934961299)),
 (1995, np.float64(0.11654330934961299)),
 (1163, np.float64(0.11633501014942217)),
 (2863, np.float64(0.11633501014942217)),
 (371, np.float64(0.11470786693528087)),
 (1412, np.float64(0.11470786693528087)),
 (4091, np.float64(0.11470786693528087)),
 (1110, np.float64(0.11470786693528086)),
 (3460, np.float64(0.11382207864489444)),
 (1290, np.float64(0.11314714296070713)),
 (2784, np.float64(0.11314714296070713)),
 (3611, np.float64(0.1130250197271061)),
 (363, np.float64(0.11295649894498098)),
 (1086, np.float64(0.11264088922239573)),
 (1768, np.float64(0.11248031766646188)),
 (2317, np.float64(0.11248031766646188)),
 (794, np.float64(0.11243619908556621)),
 (2029, np.float64(0.11243619908556621)),
 (3618, np.float64(0.11243619908556621)),
 (1891, np.float64(0.1121103709342421)),
 (3552, np.float64(0.1121103709342421)),
 (2127, np.float64(0.11211037093424209)),
 (3437, np.float64(0.11211037093424209)),
 (3514, np.float64(0.11164843913471803)),
 (4728, np.float64(0.11164843913471803)),
 (311, np.float64(0.1113498335207611)),
 (206, np.float64(0.11128297681493143)),
 (897, np.float64(0.11128297681493143)),
 (1039, np.float64(0.11128297681493143)),
 (2791, np.float64(0.11128297681493143)),
 (4272, np.float64(0.11128297681493143)),
 (3208, np.float64(0.11056269107951214)),
 (17, np.float64(0.11047363533322149)),
 (2868, np.float64(0.11047363533322149)),
 (420, np.float64(0.11047363533322148)),
 (1168, np.float64(0.11037769642208697)),
 (4470, np.float64(0.11037769642208697)),
 (1694, np.float64(0.11029436104106954)),
 (2708, np.float64(0.11029436104106954)),
 (3350, np.float64(0.11029436104106954)),
 (4176, np.float64(0.11029436104106954)),
 (687, np.float64(0.11020775375559674)),
 (3177, np.float64(0.11020775375559674)),
 (2066, np.float64(0.10926834468453095)),
 (994, np.float64(0.10890655402346602)),
 (1098, np.float64(0.10890655402346601)),
 (1036, np.float64(0.10882143751650175)),
 (3155, np.float64(0.10838874619051497)),
 (3715, np.float64(0.10838874619051497)),
 (419, np.float64(0.10827043935570554)),
 (854, np.float64(0.10827043935570553)),
 (1568, np.float64(0.10822186580487339)),
 (2474, np.float64(0.10814761408717502)),
 (2875, np.float64(0.10814761408717502)),
 (3899, np.float64(0.10814761408717502)),
 (4004, np.float64(0.10814761408717502)),
 (1199, np.float64(0.108147614087175)),
 (3018, np.float64(0.108147614087175)),
 (400, np.float64(0.1074861545850028)),
 (2427, np.float64(0.1074861545850028)),
 (977, np.float64(0.10748615458500278)),
 (3004, np.float64(0.10748615458500278)),
 (215, np.float64(0.10740432270821093)),
 (660, np.float64(0.10650358071057624)),
 (2450, np.float64(0.10650358071057624)),
 (3374, np.float64(0.10650358071057624)),
 (3494, np.float64(0.10635399695598369)),
 (4312, np.float64(0.10635399695598369)),
 (275, np.float64(0.1061988488107183)),
 (330, np.float64(0.1061988488107183)),
 (404, np.float64(0.10619884881071828)),
 (843, np.float64(0.10619884881071828)),
 (1923, np.float64(0.10619884881071828)),
 (253, np.float64(0.10596258856520348)),
 (412, np.float64(0.10543316579753613)),
 (413, np.float64(0.10543316579753613)),
 (1506, np.float64(0.10543316579753613)),
 (4509, np.float64(0.10543316579753612)),
 (4329, np.float64(0.10526315789473682)),
 (3098, np.float64(0.10495671428119792)),
 (812, np.float64(0.10482137352305541)),
 (1495, np.float64(0.10471347707292386)),
 (2500, np.float64(0.10471347707292386)),
 (3191, np.float64(0.10471347707292386)),
 (107, np.float64(0.10457739712320041)),
 (4149, np.float64(0.10453584594066231)),
 (1802, np.float64(0.1045358459406623)),
 (1633, np.float64(0.1039048666932262)),
 (329, np.float64(0.1037571695799112)),
 (10, np.float64(0.10375716957991118)),
 (4599, np.float64(0.10375716957991118)),
 (16, np.float64(0.10366105360784114)),
 (2755, np.float64(0.10366105360784114)),
 (633, np.float64(0.10324514658393347)),
 (1936, np.float64(0.10301070542879114)),
 (3372, np.float64(0.10301070542879114)),
 (3656, np.float64(0.10301070542879114)),
 (813, np.float64(0.10280786170305815)),
 (271, np.float64(0.10259783520851543)),
 (524, np.float64(0.1025978352085154)),
 (1667, np.float64(0.1025978352085154)),
 (4160, np.float64(0.1025978352085154)),
 (1095, np.float64(0.10197539568091137)),
 (666, np.float64(0.10147651372376074)),
 (1518, np.float64(0.10138838820672658)),
 (174, np.float64(0.10116282977781398)),
 (635, np.float64(0.10116282977781398)),
 (2285, np.float64(0.10074907413892013)),
 (1321, np.float64(0.10039117221153818)),
 (3533, np.float64(0.10039117221153818)),
 (1461, np.float64(0.10036938356837076)),
 (123, np.float64(0.10012523486435176)),
 (2172, np.float64(0.10012523486435176)),
 (4344, np.float64(0.10012523486435176)),
 (1271, np.float64(0.09984038297885897)),
 (2114, np.float64(0.09984038297885897)),
 (2628, np.float64(0.09984038297885897)),
 (784, np.float64(0.09959431881428263)),
 (790, np.float64(0.09959431881428263)),
 (4094, np.float64(0.09959431881428263)),
 (586, np.float64(0.09953452035868789)),
 (3804, np.float64(0.09946433500242821)),
 (147, np.float64(0.0993399267798783)),
 (334, np.float64(0.0993399267798783)),
 (1818, np.float64(0.09933992677987828)),
 (2522, np.float64(0.09933992677987828)),
 (3396, np.float64(0.09933992677987828)),
 (870, np.float64(0.09883693657685835)),
 (2048, np.float64(0.09883693657685835)),
 (2897, np.float64(0.09883693657685835)),
 (256, np.float64(0.0983611844205792)),
 (320, np.float64(0.0983611844205792)),
 (1044, np.float64(0.0983611844205792)),
 (1155, np.float64(0.0983611844205792)),
 (1827, np.float64(0.0983611844205792)),
 (2490, np.float64(0.0983611844205792)),
 (3285, np.float64(0.0983611844205792)),
 (185, np.float64(0.09832102880166932)),
 (312, np.float64(0.09832102880166932)),
 (3310, np.float64(0.09832102880166932)),
 (3749, np.float64(0.09832102880166932)),
 (1274, np.float64(0.09809657456746185)),
 (3410, np.float64(0.09809657456746183)),
 (238, np.float64(0.09782319760890368)),
 (4364, np.float64(0.09782319760890368)),
 (2492, np.float64(0.09737260471306501)),
 (531, np.float64(0.097372604713065)),
 (3305, np.float64(0.09733285267845751)),
 (166, np.float64(0.09694584179118515)),
 (878, np.float64(0.09694584179118515)),
 (3764, np.float64(0.09694584179118515)),
 (4487, np.float64(0.09694584179118515)),
 (571, np.float64(0.09673016668133488)),
 (39, np.float64(0.09637388493048532)),
 (985, np.float64(0.09637388493048532)),
 (1817, np.float64(0.09637388493048532)),
 (3033, np.float64(0.09637388493048532)),
 (2442, np.float64(0.09565579045742016)),
 (151, np.float64(0.09558988911273406)),
 (459, np.float64(0.09558988911273406)),
 (1303, np.float64(0.09558988911273406)),
 (3231, np.float64(0.09558988911273406)),
 (4225, np.float64(0.09544271444636666)),
 (4597, np.float64(0.09544271444636666)),
 (704, np.float64(0.09544271444636665)),
 (1433, np.float64(0.09544271444636665)),
 (1671, np.float64(0.09529323477053277)),
 (462, np.float64(0.09515721361396129)),
 (4173, np.float64(0.09515721361396129)),
 (1892, np.float64(0.09462916232627815)),
 (535, np.float64(0.09453802374948818)),
 (823, np.float64(0.09453802374948816)),
 (2691, np.float64(0.09453802374948816)),
 (2390, np.float64(0.09428928580058928)),
 (2713, np.float64(0.09428928580058928)),
 (3994, np.float64(0.09428928580058928)),
 (1285, np.float64(0.0936585811581694)),
 (4651, np.float64(0.0936585811581694)),
 (1192, np.float64(0.09365858115816939)),
 (1559, np.float64(0.09365858115816939)),
 (2152, np.float64(0.09304036594559835)),
 (1617, np.float64(0.09280323373346189)),
 (1743, np.float64(0.09280323373346189)),
 (809, np.float64(0.09271726499455304)),
 (1510, np.float64(0.09271726499455304)),
 (333, np.float64(0.09210526315789472)),
 (2829, np.float64(0.09210526315789472)),
 (814, np.float64(0.09197090092274487)),
 (1525, np.float64(0.09197090092274487)),
 (4321, np.float64(0.09197090092274487)),
 (4691, np.float64(0.09197090092274487)),
 (585, np.float64(0.09197090092274486)),
 (4000, np.float64(0.09183979479633063)),
 (4647, np.float64(0.09183979479633063)),
 (418, np.float64(0.0917662935482247)),
 (1569, np.float64(0.0917662935482247)),
 (3948, np.float64(0.0917662935482247)),
 (3197, np.float64(0.09176629354822469)),
 (2258, np.float64(0.09116056881941459)),
 (246, np.float64(0.09091675835657292)),

In [105]:
def recommend(movie):
    movie_index = movies[movies["title"] == movie].index[0]

    distances = similarity[movie_index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )

    recommendations = []

    for i in movie_list[1:6]:
        movie_index = i[0]
        similarity_score = i[1]

        title = movies.iloc[movie_index]["title"]
        movie_id = movies.iloc[movie_index]["id"]

        poster = get_poster(movie_id)

        recommendations.append((title, similarity_score, poster))

    return recommendations

In [107]:
recommend("Inception")

NameError: name 'get_poster' is not defined

In [ ]:
recommend('Titanic')

The Notebook
Romance & Cigarettes
Captain Phillips
Veer-Zaara
Four Weddings and a Funeral

In [ ]:
movies.columns.tolist()

['budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count']

In [ ]:
df.columns.tolist()

['title', 'genres', 'keywords', 'overview', 'cast', 'crew', 'tags']

In [ ]:
df['id'] = movies['id']

In [ ]:
df[['id', 'title', 'tags']].head()

,id,title,tags
0,19995,Avatar,action adventur fantasi scienc fiction cultur ...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drug abus exot i...
2,206647,Spectre,action adventur crime spi base on novel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,49529,John Carter,action adventur scienc fiction base on novel m...

In [ ]:
import pickle

with open("movies.pkl", "wb") as file:
    pickle.dump(df, file)

with open("similarity.pkl", "wb") as file:
    pickle.dump(similarity, file)

print("Saved!")

Saved!

In [ ]:
df['id'] = movies['id']
df[['id', 'title', 'tags']].head()

,id,title,tags
0,19995,Avatar,action adventur fantasi scienc fiction cultur ...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drug abus exot i...
2,206647,Spectre,action adventur crime spi base on novel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,49529,John Carter,action adventur scienc fiction base on novel m...